# Generated by Django 5.2.13 on 2026-04-30 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('core', '0001_initial'),
        ('operacional', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('enviado', 'Enviado ao Fornecedor'), ('confirmado', 'Confirmado'), ('recebido_parcial', 'Recebido Parcialmente'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='rascunho', max_length=20)),
                ('data_emissao', models.DateTimeField(auto_now_add=True)),
                ('data_prevista_entrega', models.DateField(blank=True, null=True)),
                ('valor_total_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_compra', to='core.fornecedor')),
            ],
            options={
                'verbose_name': 'Pedido de Compra',
                'verbose_name_plural': 'Pedidos de Compra',
                'db_table': 'sup_pedido_compra',
            },
        ),
        migrations.CreateModel(
            name='Requisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('preliminar', 'Preliminar'), ('confirmada', 'Confirmada'), ('complementar', 'Complementar')], default='preliminar', max_length=20)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_cotacao', 'Em Cotação'), ('aprovada', 'Aprovada'), ('parcial', 'Parcialmente Atendida'), ('atendida', 'Atendida'), ('cancelada', 'Cancelada')], default='aberta', max_length=20)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisicoes', to='operacional.ordemservico')),
            ],
            options={
                'verbose_name': 'Requisição de Compra',
                'verbose_name_plural': 'Requisições de Compra',
                'db_table': 'sup_requisicao',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemRequisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('status_compra', models.CharField(choices=[('pendente', 'Pendente'), ('cotado', 'Cotado'), ('comprado', 'Comprado'), ('recebido', 'Recebido'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('valor_spot_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_requisicao', to='core.fornecedor')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_requisicao', to='catalogo.produtocatalogo')),
                ('pedido_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens', to='suprimentos.pedidocompra')),
                ('requisicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='suprimentos.requisicao')),
            ],
            options={
                'verbose_name': 'Item de Requisição',
                'verbose_name_plural': 'Itens de Requisição',
                'db_table': 'sup_item_requisicao',
            },
        ),
    ]
