# Generated by Django 5.2.13 on 2026-04-30 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_aplicacaomotor_componente_referenciafabricante'),
        ('core', '0001_initial'),
        ('suprimentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemrequisicao',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_requisicao', to='catalogo.componente'),
        ),
        migrations.CreateModel(
            name='EntradaNFe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_acesso_nfe', models.CharField(help_text='44 dígitos numéricos', max_length=44, unique=True, verbose_name='Chave de Acesso NFe')),
                ('data_emissao', models.DateField(verbose_name='Data de Emissão')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas_nfe', to='core.fornecedor')),
            ],
            options={
                'verbose_name': 'Entrada NFe',
                'verbose_name_plural': 'Entradas NFe',
                'db_table': 'sup_entrada_nfe',
                'ordering': ['-data_emissao'],
            },
        ),
        migrations.CreateModel(
            name='ItemNFe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_unitario_compra', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Unitário (R$)')),
                ('quantidade', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Quantidade')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras_nfe', to='catalogo.componente', verbose_name='Componente Genérico')),
                ('entrada_nfe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='suprimentos.entradanfe', verbose_name='NFe')),
            ],
            options={
                'verbose_name': 'Item da NFe',
                'verbose_name_plural': 'Itens da NFe',
                'db_table': 'sup_item_nfe',
            },
        ),
    ]
