# Generated by Django 5.2.13 on 2026-06-11 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_empresafilial_tipo_empresa'),
        ('suprimentos', '0002_alter_itemrequisicao_produto_entradanfe_itemnfe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradanfe',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas_nfe', to='core.cliente'),
        ),
        migrations.AlterField(
            model_name='itemrequisicao',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_requisicao', to='core.cliente'),
        ),
        migrations.AlterField(
            model_name='pedidocompra',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_compra', to='core.cliente'),
        ),
    ]
