# Generated by Django 5.2.13 on 2026-07-03 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_cliente_cpf_cnpj_and_more'),
        ('suprimentos', '0003_alter_entradanfe_fornecedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradanfe',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='core.empresafilial', verbose_name='Tenant (Empresa)'),
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='core.empresafilial', verbose_name='Tenant (Empresa)'),
        ),
        migrations.AddField(
            model_name='requisicao',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='core.empresafilial', verbose_name='Tenant (Empresa)'),
        ),
    ]
