# Generated by Django 5.2.13 on 2026-07-03 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_alter_componente_codigo_interno'),
        ('core', '0010_alter_cliente_cpf_cnpj_and_more'),
        ('suprimentos', '0004_entradanfe_tenant_pedidocompra_tenant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalizacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileira', models.CharField(help_text='Corredor/rua do depósito. Ex: A, B, AA.', max_length=20, verbose_name='Fileira')),
                ('lado', models.CharField(choices=[('E', 'Esquerda'), ('D', 'Direita')], help_text='E = Esquerda, D = Direita.', max_length=1, verbose_name='Lado')),
                ('nivel', models.PositiveSmallIntegerField(help_text='Andar da prateleira (1 = inferior).', verbose_name='Nível')),
                ('bloco', models.CharField(help_text='Zona/seção. Ex: B1, B2.', max_length=10, verbose_name='Bloco')),
                ('codigo', models.CharField(help_text='Auto-gerado: FILEIRA-LADO-NÍVEL-BLOCO. Ex: A-E-2-B1.', max_length=50, verbose_name='Código da Localização')),
                ('capacidade', models.PositiveIntegerField(default=0, help_text='Capacidade máxima da posição (0 = sem limite).', verbose_name='Capacidade')),
                ('quantidade', models.PositiveIntegerField(default=0, help_text='Quantidade do componente armazenada nesta posição.', verbose_name='Quantidade Atual')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localizacoes', to='catalogo.componente', verbose_name='Componente')),
                ('tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='core.empresafilial', verbose_name='Tenant (Empresa)')),
            ],
            options={
                'verbose_name': 'Localização de Estoque',
                'verbose_name_plural': 'Localizações de Estoque',
                'db_table': 'sup_localizacao_estoque',
                'ordering': ['fileira', 'lado', 'nivel', 'bloco'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'codigo'), name='uq_sup_localizacao_tenant_codigo')],
            },
        ),
    ]
