# Generated by Django 5.2.13 on 2026-07-03 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suprimentos', '0005_localizacaoestoque'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localizacaoestoque',
            options={'ordering': ['local', 'sala', 'corredor', 'lado', 'bloco', 'prateleira'], 'verbose_name': 'Localização de Estoque', 'verbose_name_plural': 'Localizações de Estoque'},
        ),
        migrations.RemoveField(
            model_name='localizacaoestoque',
            name='componente',
        ),
        migrations.RemoveField(
            model_name='localizacaoestoque',
            name='fileira',
        ),
        migrations.RemoveField(
            model_name='localizacaoestoque',
            name='nivel',
        ),
        migrations.AddField(
            model_name='localizacaoestoque',
            name='corredor',
            field=models.CharField(default='', help_text='Corredor/rua do depósito. Ex: C01, C02.', max_length=20, verbose_name='Corredor'),
        ),
        migrations.AddField(
            model_name='localizacaoestoque',
            name='local',
            field=models.CharField(default='', help_text='Local/filial do depósito. Ex: MATRIZ, FILIAL2.', max_length=50, verbose_name='Local'),
        ),
        migrations.AddField(
            model_name='localizacaoestoque',
            name='prateleira',
            field=models.CharField(default='', help_text='Nº da prateleira. Ex: P01, P02.', max_length=10, verbose_name='Prateleira'),
        ),
        migrations.AddField(
            model_name='localizacaoestoque',
            name='sala',
            field=models.CharField(default='', help_text='Sala do depósito. Ex: S01, S02.', max_length=20, verbose_name='Sala'),
        ),
        migrations.AlterField(
            model_name='localizacaoestoque',
            name='bloco',
            field=models.CharField(default='', help_text='Bloco/seção. Ex: B01, B02.', max_length=10, verbose_name='Bloco'),
        ),
        migrations.AlterField(
            model_name='localizacaoestoque',
            name='codigo',
            field=models.CharField(default='', help_text='Auto-gerado: LOCAL-SALA-CORREDOR-LADO-BLOCO-PRATELEIRA. Ex: MATRIZ-S01-C01-E-B01-P01.', max_length=100, verbose_name='Código da Posição'),
        ),
        migrations.AlterField(
            model_name='localizacaoestoque',
            name='lado',
            field=models.CharField(choices=[('E', 'Esquerda'), ('D', 'Direita')], default='E', help_text='E = Esquerda, D = Direita.', max_length=1, verbose_name='Lado'),
        ),
        migrations.AlterField(
            model_name='localizacaoestoque',
            name='quantidade',
            field=models.PositiveIntegerField(default=0, help_text='Quantidade de itens armazenados nesta posição.', verbose_name='Quantidade Atual'),
        ),
    ]
