# Generated by Django 5.2.13 on 2026-04-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('unidade', models.CharField(default='UN', help_text='Ex: UN, LT, KG, MT.', max_length=10, verbose_name='Unidade')),
                ('custo_medio', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Custo Médio (R$)')),
                ('preco_venda', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Preço de Venda (R$)')),
                ('ponto_pedido', models.PositiveIntegerField(default=0, help_text='Qtd mínima para gerar alerta de reposição.', verbose_name='Ponto de Pedido')),
                ('estoque_atual', models.PositiveIntegerField(default=0, verbose_name='Estoque Atual')),
                ('flag_jit', models.BooleanField(default=False, help_text='Se True, peça é comprada sob demanda (sem estoque).', verbose_name='Just-In-Time')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Produto (Catálogo)',
                'verbose_name_plural': 'Produtos (Catálogo)',
                'db_table': 'prod_catalogo',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='ServicoCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('tempo_padrao', models.DecimalField(decimal_places=2, default=1, help_text='Tempo padrão em horas para executar o serviço.', max_digits=6, verbose_name='Tempo Padrão (h)')),
                ('preco_base', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Preço Base (R$)')),
                ('especialidade', models.CharField(blank=True, default='', help_text='Ex: Motor, Elétrica, Funilaria.', max_length=100, verbose_name='Especialidade')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Serviço (Catálogo)',
                'verbose_name_plural': 'Serviços (Catálogo)',
                'db_table': 'serv_catalogo',
                'ordering': ['descricao'],
            },
        ),
    ]
