# Generated by Django 5.2.13 on 2026-04-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AplicacaoMotor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoes', models.TextField(blank=True, default='', help_text='Ex: Apenas modelos à gasolina.', verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Aplicação de Motor',
                'verbose_name_plural': 'Aplicações de Motores',
                'db_table': 'prod_aplicacao_motor',
            },
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_interno', models.CharField(help_text='Ex: RET-VAL-001 (SKU central)', max_length=50, unique=True, verbose_name='Código Interno')),
                ('tipo_componente', models.CharField(choices=[('RETENTOR', 'Retentor'), ('JUNTA', 'Junta'), ('FILTRO', 'Filtro'), ('CORREIA', 'Correia'), ('OLEO', 'Óleo'), ('OUTRO', 'Outro')], default='OUTRO', max_length=50, verbose_name='Tipo de Componente')),
                ('descricao_generica', models.CharField(help_text='Ex: Retentor Haste de válvula', max_length=255, verbose_name='Descrição Genérica')),
                ('medidas_tecnicas', models.CharField(blank=True, default='', help_text='Ex: 8,00x10,90x10,00', max_length=100, verbose_name='Medidas Técnicas')),
                ('unidade', models.CharField(default='UN', help_text='Ex: UN, LT, KG, MT.', max_length=10, verbose_name='Unidade')),
                ('custo_medio_ponderado', models.DecimalField(decimal_places=2, default=0, help_text='Atualizado automaticamente pela entrada de NFe.', max_digits=12, verbose_name='Custo Médio Ponderado (R$)')),
                ('preco_venda', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Preço de Venda (R$)')),
                ('ponto_pedido', models.PositiveIntegerField(default=0, help_text='Qtd mínima para gerar alerta de reposição.', verbose_name='Ponto de Pedido')),
                ('estoque_atual', models.PositiveIntegerField(default=0, verbose_name='Estoque Atual')),
                ('flag_jit', models.BooleanField(default=False, help_text='Se True, peça é comprada sob demanda (sem estoque).', verbose_name='Just-In-Time')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Componente',
                'verbose_name_plural': 'Componentes',
                'db_table': 'prod_componente',
                'ordering': ['descricao_generica'],
            },
        ),
        migrations.CreateModel(
            name='ReferenciaFabricante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_fabricante', models.CharField(help_text='Código impresso na caixa/catálogo.', max_length=100, verbose_name='Código do Fabricante')),
                ('material_construcao', models.CharField(blank=True, default='', help_text='Ex: NBR, MVQ', max_length=100, verbose_name='Material de Construção')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Referência de Fabricante',
                'verbose_name_plural': 'Referências de Fabricantes',
                'db_table': 'prod_referencia_fabricante',
            },
        ),
    ]
