# Generated by Django 5.2.13 on 2026-04-30 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_aplicacaomotor_componente_referenciafabricante'),
        ('operacional', '0002_alter_orcamentoitem_produto'),
        ('suprimentos', '0002_alter_itemrequisicao_produto_entradanfe_itemnfe'),
        ('veiculos', '0002_alter_versao_motorizacao_motor_versao_motor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProdutoCatalogo',
        ),
        migrations.AddField(
            model_name='aplicacaomotor',
            name='motor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicacoes_componentes', to='veiculos.motor', verbose_name='Motor'),
        ),
        migrations.AddField(
            model_name='aplicacaomotor',
            name='componente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicacoes_motor', to='catalogo.componente', verbose_name='Componente'),
        ),
        migrations.AddField(
            model_name='referenciafabricante',
            name='componente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencias', to='catalogo.componente', verbose_name='Componente Genérico'),
        ),
        migrations.AddField(
            model_name='referenciafabricante',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referencias_produtos', to='veiculos.marca', verbose_name='Marca/Fabricante'),
        ),
        migrations.AddConstraint(
            model_name='aplicacaomotor',
            constraint=models.UniqueConstraint(fields=('componente', 'motor'), name='uq_prod_aplicacao_componente_motor'),
        ),
        migrations.AddConstraint(
            model_name='referenciafabricante',
            constraint=models.UniqueConstraint(fields=('marca', 'codigo_fabricante'), name='uq_prod_referencia_marca_codigo'),
        ),
    ]
