# Generated by Django 5.2.13 on 2026-06-11 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_delete_produtocatalogo_aplicacaomotor_motor_and_more'),
        ('veiculos', '0003_categoria_remove_modelo_categoria_veiculo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AplicacaoVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoes', models.TextField(blank=True, default='', help_text='Ex: Apenas modelos flex.', verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicacoes_veiculos', to='catalogo.componente', verbose_name='Componente')),
                ('versao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicacoes_componentes', to='veiculos.versao', verbose_name='Versão do Veículo')),
            ],
            options={
                'verbose_name': 'Aplicação de Veículo',
                'verbose_name_plural': 'Aplicações de Veículos',
                'db_table': 'prod_aplicacao_veiculo',
                'constraints': [models.UniqueConstraint(fields=('componente', 'versao'), name='uq_prod_aplicacao_componente_versao')],
            },
        ),
    ]
