# Generated by Django 5.2.13 on 2026-06-12 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_aplicacaoveiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componente',
            name='codigo_interno',
            field=models.CharField(blank=True, help_text='Ex: RET-001-10X200', max_length=50, unique=True, verbose_name='Código Interno'),
        ),
    ]
