# Generated by Django 5.2.13 on 2026-04-30 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentoSocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_pessoal', models.CharField(choices=[('saude', 'Saúde'), ('moradia', 'Moradia'), ('educacao', 'Educação'), ('transporte', 'Transporte'), ('alimentacao', 'Alimentação'), ('lazer', 'Lazer'), ('investimento', 'Investimento'), ('prolabore', 'Pró-labore'), ('outros', 'Outros')], default='outros', max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('descricao', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('socio', models.ForeignKey(help_text='Colaborador com perfil de sócio.', on_delete=django.db.models.deletion.PROTECT, related_name='movimentos_societarios', to='core.colaborador')),
                ('transacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentos_socio', to='financeiro.transacao')),
            ],
            options={
                'verbose_name': 'Movimento de Sócio',
                'verbose_name_plural': 'Movimentos de Sócios',
                'db_table': 'soc_movimento_socio',
                'ordering': ['-criado_em'],
            },
        ),
    ]
