# Generated by Django 5.2.13 on 2026-04-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_razao', models.CharField(max_length=255, verbose_name='Nome / Razão Social')),
                ('cpf_cnpj', models.CharField(max_length=18, unique=True, verbose_name='CPF / CNPJ')),
                ('telefone', models.CharField(blank=True, default='', max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail')),
                ('endereco', models.TextField(blank=True, default='', verbose_name='Endereço')),
                ('limite_credito', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Limite de Crédito')),
                ('categoria_contrato', models.CharField(choices=[('avulso', 'Avulso'), ('contrato', 'Contrato'), ('frotista', 'Frotista')], default='avulso', max_length=20, verbose_name='Categoria de Contrato')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'core_cliente',
                'ordering': ['nome_razao'],
            },
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('cargo', models.CharField(blank=True, default='', max_length=100, verbose_name='Cargo')),
                ('custo_hora', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Custo Hora (R$)')),
                ('especialidade', models.CharField(blank=True, default='', help_text='Ex: Motor, Elétrica, Funilaria.', max_length=100, verbose_name='Especialidade')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
                'db_table': 'core_colaborador',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='EmpresaFilial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=255, verbose_name='Razão Social')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('inscricao_estadual', models.CharField(blank=True, default='', max_length=20, verbose_name='Inscrição Estadual')),
                ('endereco', models.TextField(blank=True, default='', verbose_name='Endereço')),
                ('telefone', models.CharField(blank=True, default='', max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail')),
                ('configuracoes', models.JSONField(blank=True, default=dict, help_text='Parâmetros específicos da filial (JSON).', verbose_name='Configurações')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Empresa / Filial',
                'verbose_name_plural': 'Empresas / Filiais',
                'db_table': 'core_empresa_filial',
                'ordering': ['razao_social'],
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=255, verbose_name='Razão Social')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('telefone', models.CharField(blank=True, default='', max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail')),
                ('prazo_faturamento', models.PositiveIntegerField(default=30, verbose_name='Prazo de Faturamento (dias)')),
                ('lead_time', models.PositiveIntegerField(default=3, help_text='Tempo médio de entrega em dias.', verbose_name='Lead Time (dias)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'db_table': 'core_fornecedor',
                'ordering': ['razao_social'],
            },
        ),
    ]
