# Generated by Django 5.2.13 on 2026-05-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='apelido_fantasia',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Apelido / Nome Fantasia'),
        ),
    ]
