# Generated by Django 5.2.13 on 2026-05-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cliente_apelido_fantasia'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cep',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.CharField(blank=True, default='', max_length=2, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.TextField(blank=True, default='', verbose_name='Endereço / Logradouro'),
        ),
    ]
