# Generated by Django 5.2.13 on 2026-05-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cliente_bairro_cliente_cep_cliente_cidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, default='Sistema', max_length=100, verbose_name='Usuário')),
                ('tabela', models.CharField(max_length=100, verbose_name='Tabela')),
                ('registro_id', models.IntegerField(verbose_name='ID do Registro')),
                ('acao', models.CharField(max_length=50, verbose_name='Ação')),
                ('detalhes', models.JSONField(blank=True, default=dict, verbose_name='Detalhes')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'db_table': 'core_audit_log',
                'ordering': ['-timestamp'],
            },
        ),
    ]
