# Generated by Django 5.2.13 on 2026-05-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='detalhamento',
            field=models.TextField(blank=True, default='', verbose_name='Detalhamento das Alterações'),
        ),
    ]
