# Generated by Django 5.2.13 on 2026-06-11 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auditlog_enhancements'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresafilial',
            name='tipo_empresa',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('fornecedor', 'Fornecedor'), ('ambos', 'Cliente e Fornecedor'), ('matriz_filial', 'Matriz / Filial do Sistema')], default='matriz_filial', max_length=20, verbose_name='Tipo de Empresa'),
        ),
    ]
