# Generated by Django 5.2.13 on 2026-06-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_empresafilial_tipo_empresa'),
        ('operacional', '0003_alter_orcamentoitem_fornecedor'),
        ('suprimentos', '0003_alter_entradanfe_fornecedor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fornecedor',
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nome_razao'], 'verbose_name': 'Parceiro de Negócios', 'verbose_name_plural': 'Parceiros de Negócios'},
        ),
        migrations.AddField(
            model_name='cliente',
            name='is_cliente',
            field=models.BooleanField(default=True, verbose_name='É Cliente?'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='is_fornecedor',
            field=models.BooleanField(default=False, verbose_name='É Fornecedor?'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='lead_time',
            field=models.PositiveIntegerField(default=3, help_text='Tempo médio de entrega em dias (se fornecedor).', verbose_name='Lead Time (dias)'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='prazo_faturamento',
            field=models.PositiveIntegerField(default=30, verbose_name='Prazo de Faturamento (dias)'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_pessoa',
            field=models.CharField(choices=[('pf', 'Pessoa Física'), ('pj', 'Pessoa Jurídica')], default='pf', max_length=2, verbose_name='Tipo de Pessoa'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='categoria_contrato',
            field=models.CharField(choices=[('avulso', 'Avulso'), ('frota', 'Frota'), ('seguradora', 'Seguradora')], default='avulso', max_length=20, verbose_name='Categoria de Contrato'),
        ),
    ]
