# Generated by Django 5.2.13 on 2026-07-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_cliente_tenant_colaborador_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf_cnpj',
            field=models.CharField(max_length=18, verbose_name='CPF / CNPJ'),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(fields=('tenant', 'cpf_cnpj'), name='uq_core_cliente_tenant_cpf_cnpj'),
        ),
    ]
