# Generated by Django 5.2.13 on 2026-04-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Ex: LIMITE_VARIACAO_PCT', max_length=100, unique=True, verbose_name='Slug')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('valor_decimal', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('valor_texto', models.TextField(blank=True, default='')),
                ('nivel', models.CharField(choices=[('global', 'Global'), ('cliente', 'Por Cliente'), ('filial', 'Por Filial')], default='global', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parâmetro de Governança',
                'verbose_name_plural': 'Parâmetros de Governança',
                'db_table': 'gov_parametros',
                'ordering': ['slug'],
            },
        ),
    ]
