# Generated by Django 5.2.13 on 2026-04-30 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_marca', models.CharField(max_length=100, unique=True, verbose_name='Nome da Marca')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'db_table': 'veic_marca',
                'ordering': ['nome_marca'],
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_modelo', models.CharField(max_length=150, verbose_name='Nome do Modelo')),
                ('categoria_veiculo', models.CharField(choices=[('carro', 'Carro'), ('moto', 'Moto'), ('caminhao', 'Caminhão'), ('onibus', 'Ônibus'), ('utilitario', 'Utilitário'), ('outro', 'Outro')], default='carro', max_length=20, verbose_name='Categoria do Veículo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modelos', to='veiculos.marca', verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Modelo',
                'verbose_name_plural': 'Modelos',
                'db_table': 'veic_modelo',
                'ordering': ['marca__nome_marca', 'nome_modelo'],
            },
        ),
        migrations.CreateModel(
            name='Versao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_versao', models.CharField(max_length=150, verbose_name='Nome da Versão/Motorização')),
                ('codigo_fipe', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Código FIPE')),
                ('motorizacao', models.CharField(blank=True, default='', max_length=50, verbose_name='Motorização')),
                ('combustivel', models.CharField(choices=[('G', 'Gasolina'), ('A', 'Álcool'), ('F', 'Flex'), ('D', 'Diesel'), ('E', 'Elétrico'), ('H', 'Híbrido')], default='F', max_length=1, verbose_name='Combustível')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versoes', to='veiculos.modelo', verbose_name='Modelo')),
            ],
            options={
                'verbose_name': 'Versão',
                'verbose_name_plural': 'Versões',
                'db_table': 'veic_versao',
                'ordering': ['modelo__nome_modelo', 'nome_versao'],
            },
        ),
        migrations.CreateModel(
            name='CotacaoMercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_referencia', models.PositiveSmallIntegerField(verbose_name='Ano de Referência')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor de Mercado (R$)')),
                ('mes_referencia', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Mês de Referência')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('versao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotacoes', to='veiculos.versao', verbose_name='Versão')),
            ],
            options={
                'verbose_name': 'Cotação de Mercado',
                'verbose_name_plural': 'Cotações de Mercado',
                'db_table': 'veic_cotacao_mercado',
                'ordering': ['-ano_referencia', 'versao'],
            },
        ),
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True, verbose_name='Placa')),
                ('chassi', models.CharField(max_length=17, unique=True, verbose_name='Chassi')),
                ('ano_fabricacao', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ano de Fabricação')),
                ('cor', models.CharField(blank=True, default='', max_length=50, verbose_name='Cor')),
                ('km', models.PositiveIntegerField(default=0, verbose_name='Quilometragem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to='core.cliente', verbose_name='Cliente')),
                ('versao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ativos', to='veiculos.versao', verbose_name='Versão')),
            ],
            options={
                'verbose_name': 'Veículo (Ativo)',
                'verbose_name_plural': 'Veículos (Ativos)',
                'db_table': 'veic_ativo',
                'ordering': ['placa'],
            },
        ),
        migrations.AddConstraint(
            model_name='modelo',
            constraint=models.UniqueConstraint(fields=('marca', 'nome_modelo'), name='uq_veic_modelo_marca_nome'),
        ),
        migrations.AddConstraint(
            model_name='cotacaomercado',
            constraint=models.UniqueConstraint(fields=('versao', 'ano_referencia', 'mes_referencia'), name='uq_veic_cotacao_versao_ano_mes'),
        ),
    ]
