# Generated by Django 5.2.13 on 2026-04-30 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versao',
            name='motorizacao',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Motorização (Texto)'),
        ),
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_familia', models.CharField(help_text='Ex: FIASA, SEVEL, AP, FIRE', max_length=50, verbose_name='Código da Família')),
                ('cilindradas', models.CharField(help_text='Ex: 1.0, 1.6, 2.0', max_length=20, verbose_name='Cilindradas')),
                ('valvulas', models.CharField(help_text='Ex: 8V, 16V', max_length=10, verbose_name='Válvulas')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Motor',
                'verbose_name_plural': 'Motores',
                'db_table': 'veic_motor',
                'ordering': ['codigo_familia', 'cilindradas'],
                'constraints': [models.UniqueConstraint(fields=('codigo_familia', 'cilindradas', 'valvulas'), name='uq_veic_motor_familia_cilindradas_valvulas')],
            },
        ),
        migrations.AddField(
            model_name='versao',
            name='motor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versoes', to='veiculos.motor', verbose_name='Motor Técnico'),
        ),
    ]
