# Generated by Django 5.2.13 on 2026-04-30 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('operacional', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Conta')),
                ('tipo', models.CharField(help_text='Ex: Corrente, Poupança, Caixa, Cartão', max_length=50, verbose_name='Tipo')),
                ('taxa_administrativa_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taxa ADM (%)')),
                ('prazo_recebimento_dias', models.PositiveIntegerField(default=0, verbose_name='Prazo Recebimento (dias)')),
                ('saldo_atual', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Saldo Atual')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Conta Bancária',
                'verbose_name_plural': 'Contas Bancárias',
                'db_table': 'fin_conta_bancaria',
            },
        ),
        migrations.CreateModel(
            name='PlanoContas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ex: 2.1.1.1.0', max_length=20, unique=True, verbose_name='Código')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('tipo_natureza', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa'), ('ativo', 'Ativo'), ('passivo', 'Passivo')], max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plano de Contas',
                'verbose_name_plural': 'Plano de Contas',
                'db_table': 'fin_plano_contas',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='CicloOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveSmallIntegerField(verbose_name='Ano')),
                ('quadrimestre', models.PositiveSmallIntegerField(help_text='1, 2 ou 3', verbose_name='Quadrimestre')),
                ('status', models.CharField(choices=[('planejamento', 'Em Planejamento'), ('ativo', 'Ativo'), ('encerrado', 'Encerrado')], default='planejamento', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ciclo Orçamentário',
                'verbose_name_plural': 'Ciclos Orçamentários',
                'db_table': 'fin_ciclo_orcamento',
                'constraints': [models.UniqueConstraint(fields=('ano', 'quadrimestre'), name='uq_fin_ciclo_ano_quad')],
            },
        ),
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_original', models.DecimalField(decimal_places=2, max_digits=14)),
                ('valor_atualizado', models.DecimalField(decimal_places=2, max_digits=14)),
                ('vencimento', models.DateField()),
                ('data_competencia', models.DateField()),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('parcial', 'Parcialmente Pago'), ('pago', 'Pago'), ('renegociado', 'Renegociado'), ('cancelado', 'Cancelado')], default='aberto', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='titulos', to='core.cliente')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='titulos', to='operacional.ordemservico')),
            ],
            options={
                'verbose_name': 'Título Financeiro',
                'verbose_name_plural': 'Títulos Financeiros',
                'db_table': 'fin_titulo',
                'ordering': ['vencimento'],
            },
        ),
        migrations.CreateModel(
            name='Renegociacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_acrescimo', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('motivo', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('titulo_antigo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='renegociacoes_origem', to='financeiro.titulo')),
                ('titulo_novo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='renegociacoes_destino', to='financeiro.titulo')),
            ],
            options={
                'verbose_name': 'Renegociação',
                'verbose_name_plural': 'Renegociações',
                'db_table': 'fin_renegociacao',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('juros', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('multa', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data_caixa', models.DateField()),
                ('delta_variacao_os', models.DecimalField(decimal_places=2, default=0, help_text='Desvio lançado automaticamente na conta 2.1.5.0.0.', max_digits=12)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('conta_bancaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transacoes', to='financeiro.contabancaria')),
                ('plano_contas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacoes', to='financeiro.planocontas')),
                ('titulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='financeiro.titulo')),
            ],
            options={
                'verbose_name': 'Transação Financeira',
                'verbose_name_plural': 'Transações Financeiras',
                'db_table': 'fin_transacao',
                'ordering': ['-data_caixa'],
            },
        ),
        migrations.CreateModel(
            name='MetaConta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_valor', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Meta R$')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas', to='financeiro.cicloorcamento')),
                ('plano_contas', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='metas', to='financeiro.planocontas')),
            ],
            options={
                'verbose_name': 'Meta por Conta',
                'verbose_name_plural': 'Metas por Conta',
                'db_table': 'fin_meta_conta',
                'constraints': [models.UniqueConstraint(fields=('ciclo', 'plano_contas'), name='uq_fin_meta_ciclo_conta')],
            },
        ),
    ]
