# Generated by Django 5.2.13 on 2026-05-01 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planocontas',
            name='nivel',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Nível'),
        ),
    ]
