# Generated by Django 5.2.13 on 2026-07-03 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_cliente_cpf_cnpj_and_more'),
        ('financeiro', '0002_planocontas_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cicloorcamento',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='core.empresafilial', verbose_name='Tenant (Empresa)'),
        ),
        migrations.AddField(
            model_name='contabancaria',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='core.empresafilial', verbose_name='Tenant (Empresa)'),
        ),
        migrations.AddField(
            model_name='metaconta',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='core.empresafilial', verbose_name='Tenant (Empresa)'),
        ),
        migrations.AddField(
            model_name='renegociacao',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='core.empresafilial', verbose_name='Tenant (Empresa)'),
        ),
        migrations.AddField(
            model_name='titulo',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='core.empresafilial', verbose_name='Tenant (Empresa)'),
        ),
        migrations.AddField(
            model_name='transacao',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='core.empresafilial', verbose_name='Tenant (Empresa)'),
        ),
    ]
