# Generated by Django 5.2.13 on 2026-04-30 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('core', '0001_initial'),
        ('veiculos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.PositiveSmallIntegerField(default=1, verbose_name='Versão')),
                ('is_active', models.BooleanField(default=True, help_text='Apenas uma versão deve estar ativa por OS.', verbose_name='Versão Ativa')),
                ('status_aprovacao', models.CharField(choices=[('rascunho', 'Rascunho'), ('enviado', 'Enviado ao Cliente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='rascunho', max_length=20, verbose_name='Status de Aprovação')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Valor Total (R$)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamentos',
                'db_table': 'op_orcamento',
                'ordering': ['os', 'versao'],
            },
        ),
        migrations.CreateModel(
            name='RecursoFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Recurso')),
                ('tipo', models.CharField(help_text='Ex: Box, Rampa, Elevador', max_length=50, verbose_name='Tipo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Recurso Físico',
                'verbose_name_plural': 'Recursos Físicos',
                'db_table': 'op_recurso_fisico',
            },
        ),
        migrations.CreateModel(
            name='OrcamentoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(choices=[('inicial', 'Inicial'), ('extra', 'Extra (Aditivo)')], default='inicial', max_length=10, verbose_name='Origem')),
                ('quantidade', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Quantidade')),
                ('valor_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Estimado (R$)')),
                ('is_terceiro', models.BooleanField(default=False, verbose_name='É Serviço Terceirizado?')),
                ('lead_time_previsto_dias', models.PositiveIntegerField(default=0, verbose_name='Lead Time Previsto (dias)')),
                ('valor_real', models.DecimalField(blank=True, decimal_places=2, help_text='Preenchido após execução. Trigger calcula Delta_Variacao_OS.', max_digits=12, null=True, verbose_name='Valor Real (R$)')),
                ('delta_variacao_os', models.DecimalField(decimal_places=2, default=0, help_text='Desvio = Valor_Real - Valor_Estimado. Lançado na conta 2.1.5.0.0.', max_digits=12, verbose_name='Delta Variação OS (R$)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicos_terceirizados', to='core.fornecedor', verbose_name='Fornecedor (Terceiro)')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='operacional.orcamento', verbose_name='Orçamento')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orcamento_itens', to='catalogo.produtocatalogo', verbose_name='Produto (Peça)')),
                ('servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orcamento_itens', to='catalogo.servicocatalogo', verbose_name='Serviço (MO)')),
            ],
            options={
                'verbose_name': 'Item de Orçamento',
                'verbose_name_plural': 'Itens de Orçamento',
                'db_table': 'op_orcamento_item',
            },
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('em_diagnostico', 'Em Diagnóstico'), ('aguardando_aprovacao', 'Aguardando Aprovação'), ('em_execucao', 'Em Execução'), ('aguardando_pecas', 'Aguardando Peças'), ('concluida', 'Concluída'), ('entregue', 'Entregue'), ('cancelada', 'Cancelada')], default='em_diagnostico', max_length=30, verbose_name='Status')),
                ('descricao_problema', models.TextField(blank=True, default='', verbose_name='Descrição do Problema')),
                ('km_entrada', models.PositiveIntegerField(default=0, verbose_name='KM na Entrada')),
                ('data_in', models.DateTimeField(auto_now_add=True, verbose_name='Data de Entrada')),
                ('data_out', models.DateTimeField(blank=True, null=True, verbose_name='Data de Saída')),
                ('observacoes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('tempo_real_minutos', models.PositiveIntegerField(default=0, help_text='Feedback de execução (RF-OP-10)', verbose_name='Tempo Real (min)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_servico', to='veiculos.ativo', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Ordem de Serviço',
                'verbose_name_plural': 'Ordens de Serviço',
                'db_table': 'op_ordem_servico',
                'ordering': ['-data_in'],
            },
        ),
        migrations.AddField(
            model_name='orcamento',
            name='os',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos', to='operacional.ordemservico', verbose_name='Ordem de Serviço'),
        ),
        migrations.CreateModel(
            name='HistoricoAprovacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_antes', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Valor Antes (R$)')),
                ('valor_aditivo', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Valor do Aditivo (R$)')),
                ('justificativa', models.TextField(blank=True, default='', verbose_name='Justificativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('usuario_aprovador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprovacoes', to=settings.AUTH_USER_MODEL, verbose_name='Aprovador')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_aprovacao', to='operacional.ordemservico', verbose_name='Ordem de Serviço')),
            ],
            options={
                'verbose_name': 'Histórico de Aprovação',
                'verbose_name_plural': 'Históricos de Aprovação',
                'db_table': 'op_historico_aprovacao',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Alocacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(verbose_name='Data/Hora Início')),
                ('data_fim', models.DateTimeField(verbose_name='Data/Hora Fim')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('colaborador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alocacoes', to='core.colaborador')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes', to='operacional.ordemservico')),
                ('recurso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alocacoes', to='operacional.recursofisico')),
            ],
            options={
                'verbose_name': 'Alocação',
                'verbose_name_plural': 'Alocações',
                'db_table': 'op_alocacao',
                'ordering': ['data_inicio'],
            },
        ),
        migrations.AddConstraint(
            model_name='orcamento',
            constraint=models.UniqueConstraint(fields=('os', 'versao'), name='uq_op_orcamento_os_versao'),
        ),
    ]
