# Generated by Django 5.2.13 on 2026-04-30 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_aplicacaomotor_componente_referenciafabricante'),
        ('operacional', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamentoitem',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orcamento_itens', to='catalogo.componente', verbose_name='Produto (Peça)'),
        ),
    ]
