# Generated by Django 5.2.13 on 2026-06-11 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_empresafilial_tipo_empresa'),
        ('operacional', '0002_alter_orcamentoitem_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamentoitem',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicos_terceirizados', to='core.cliente', verbose_name='Fornecedor (Terceiro)'),
        ),
    ]
