# Generated by Django 5.2.13 on 2026-07-03 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_cliente_tenant_colaborador_tenant'),
        ('operacional', '0003_alter_orcamentoitem_fornecedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='core.empresafilial', verbose_name='Tenant (Empresa)'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='core.empresafilial', verbose_name='Tenant (Empresa)'),
        ),
    ]
